In [7]:
import cv2 as cv
import numpy as np

img = cv.imread('..\data\empire.jpg') # 读取RGB彩⾊图⽚
img_gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY) # RGB图转灰度图
cv.imshow('color image', img_gray) # 显示图⽚
cv.waitKey(0) # 图⽚显示时间设定， 0代表⼀直显示，直到有键盘输⼊

# cv.imwrite("img/lena2.jpg", img) # 保存图⽚
# cv.imwrite('img/lina_jpeg_quality_90.jpg', img, [int(cv.IMWRITE_JPEG_QUALITY), 90])
# cv.imwrite('img/line_png_compress_2.png', img, [int(cv.IMWRITE_PNG_COMPRESSION), 2])


-1

In [8]:
def get_image_info(image): 
    print(type(image))
    print(image.shape)
    print(image.size)
    print(image.dtype)
    pixel_data = np.array(image)
    print(pixel_data)
cv.imshow('color image', img)
get_image_info(img)


<class 'numpy.ndarray'>
(800, 569, 3)
1365600
uint8
[[[188 133  88]
  [186 131  86]
  [186 131  86]
  ...
  [250 248 247]
  [249 247 246]
  [249 247 246]]

 [[189 134  89]
  [188 133  88]
  [188 133  88]
  ...
  [249 247 246]
  [249 247 246]
  [251 247 246]]

 [[189 135  88]
  [188 134  87]
  [187 133  86]
  ...
  [250 246 245]
  [250 246 245]
  [251 247 246]]

 ...

 [[231 177 130]
  [232 178 131]
  [232 178 131]
  ...
  [ 36  40  35]
  [ 37  41  36]
  [ 37  41  35]]

 [[231 177 130]
  [232 178 131]
  [232 178 131]
  ...
  [ 37  41  36]
  [ 40  44  39]
  [ 39  43  37]]

 [[231 178 128]
  [233 180 130]
  [231 178 128]
  ...
  [ 38  42  37]
  [ 38  42  37]
  [ 37  41  35]]]
